name: 'Save a cache'
description:
  'Save Cache artifacts like dependencies and build outputs to improve workflow
  execution time'
author: 'Tâm Võ'

branding:
  icon: 'archive'
  color: 'red'

inputs:
  path:
    description: 'An explicit key for versioning the cache'
    required: true
  action:
    description: 'The file or folder to be cached'
    required: false
  cache-key:
    description: 'The path dir will cache'
    required: true
  cache-dir:
    description: 'Action will be run if not cashed yet'
    required: true
  working-directory:
    description: 'Working directory'
    required: false

outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

runs:
  using: node20
  main: dist/save/index.js
